### ISSUE TITLE
classifier training issue

### ISSUE THREAD

**Issue by Rajalakshmi-Palaniappan** [haesleinhuepf/napari-accelerated-pixel-and-object-classification#16]
Hi Robert,

Thanks for APOC!

I successfully installed napari_apoc and could create labels layer and do annotation.
In order to train a object segmenter I used Tools > Segmentation/Labelling > object segmentation (APOC), after making the necessary selections when I try to train it the following error shows up:

"TypeError: __array__() takes 1 positional argument but 2 were given"

Here is the traceback,
Traceback (most recent call last):
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari_accelerated_pixel_and_object_classification/_dock_widget.py", line 154, in train_clicked
    self.train(
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari_accelerated_pixel_and_object_classification/_dock_widget.py", line 276, in train
    classifier.train(feature_definition, annotation, images)
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/apoc/_pixel_classifier.py", line 67, in train
    features = self._make_features_potentially_multichannel(features, image)
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/apoc/_pixel_classifier.py", line 247, in _make_features_potentially_multichannel
    features = self._make_features(features, image)
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/apoc/_pixel_classifier.py", line 269, in _make_features
    features = generate_feature_stack(image, features)
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/apoc/_utils.py", line 27, in generate_feature_stack
    image = cle.push(image)
  File "/home/rajalakshmi/anaconda3/envs/napari-env/lib/python3.9/site-packages/pyclesperanto_prototype/_tier0/_push.py", line 37, in push
    return Backend.get_instance().get().from_array(np.float32(any_array))
TypeError: __array__() takes 1 positional argument but 2 were given

Thanks,
Raji

**Comment by haesleinhuepf** [comment]
Hi Raji @Rajalakshmi-Palaniappan ,

can you please let me know which version of APOC and napari-accelerated-pixel-and-object-classification you are using? Furthermore, I'd be interested in the shape of the image and the labels layer you are training on. They need to have the same shape. You can use this napari plugin to figure that out:

https://www.napari-hub.org/plugins/napari-layer-details-display

Best,
Robert

**Comment by Rajalakshmi-Palaniappan** [comment]
Hi Robert,

Thanks for replying,
I used APOC 0.7.0
         napari-accelerated-pixel-and-object-classification 0.7.3.
And from the napari plugin you mentioned I could see the layer details and they both have the same shape (1,1,2409,1668,1604). 

Please find screenshot of layer details here : https://i.imgur.com/QE2QSz6.png

Thanks,
Raji

**Comment by haesleinhuepf** [comment]
> (1,1,2409,1668,1604)

Ok, that's 5 dimensions. Could you please try again with a 3-dimensional image? Such code might help:

```
viewer.layers[0].data = viewer.layers[0].data[0,0]
```

I _think_ it would also work with 4D, but I'm not 100% sure.

Also, just a warning: This image stack appears 6 GB large (if it's 8-bit integer). Depending on which features you chose, memory conumption in the GPU may be huge. I suggest to test APOC with smaller images first.

**Comment by Rajalakshmi-Palaniappan** [comment]
Hi Robert,

I tried with 4D data, it considers the current time point and hence the annotation shape was 3D.
Since my data is large I think this error showed up
"pyopencl._cl.MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE"
However, as you said when I tried for the smaller images it worked fine!

Thanks for the help!

Best,
Raji

**Comment by haesleinhuepf** [comment]
Awesome! Thanks for reaching out Raji!

**Comment by schienstockd** [comment]
> Also, just a warning: This image stack appears 6 GB large (if it's 8-bit integer). Depending on which features you chose, memory conumption in the GPU may be huge. I suggest to test APOC with smaller images first.

Just curious what the options are to actually process a larger image. I use overlapping slices for object segmentation with subsequent merging. Do you think that could also be done here or is there a better option?

**Comment by haesleinhuepf** [comment]
Hi @schienstockd ,

yes, I also think tiling is the only way, e g. using dask:

https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/32_tiled_image_processing/tiled_nuclei_counting_quick.html

Best,
Robert
