### ISSUE TITLE
Segmentation results are not visualised

### ISSUE THREAD

**Issue by MalteMederacke** [haesleinhuepf/napari-accelerated-pixel-and-object-classification#21]
Hi, 

I am using napari-accelerated-pixel-and-object-classification-0.9.0. I think I am able to create classifier files (eg. PixelClassifier.cl), but the new label layer with the prediction doesn't come up. (Like it does in the demo video.) As I don't get any error, I am no sure what is going wrong. I am using a small 3D image.

Best,

Malte

**Comment by haesleinhuepf** [comment]
Hi @MalteMederacke ,

I cannot reproduce this issue unfortunately. Can you provide a screenshot, an exact procedure of what you do and/or an example dataset? For example, which menu are you using; from your description I presume `Tools > Segmentation / Labeling > Semantic Segmentation (APOC)`? 
It would also be interesting to see the ouput of the Napari menu `Help > Napari info`. Any hint that allows reproducing your issue is welcome.

Thanks for reporting!

Best,
Robert

**Comment by MalteMederacke** [comment]
Hi Robert, 

thanks for coming back to me so quickly! I should have more precise from the beginning, then. So here it goes:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/65277828/189734800-61e266c9-afb3-4e8a-9c14-473e5d2f1845.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/65277828/189736609-3db0333d-84a8-4c09-bc6d-012cb8bb4bef.png">

and then nothing happens.

So, I found an error massage (looked in the wrong consol, whoops):

<img width="506" alt="image" src="https://user-images.githubusercontent.com/65277828/189736095-a380706e-cec6-49ce-a0fd-030f4c3a8748.png">

My image is a stack of np arrays with the shape (z,x,y) = (276, 1787, 1379). Does this format not work?


Best,

Malte

**Comment by haesleinhuepf** [comment]
Can you click on the image in the list on the top right before training? That's necessary to select it. If that was the cause of the bug, I'll make sure the error message is more informative.

**Comment by MalteMederacke** [comment]
That was it! Glad it was such an easy miss from my side. Maybe its worth to make a dropdown like with the labels, then one can't miss it. Anyways, thank you for developing such great tools! 

Best,

Malte

**Comment by haesleinhuepf** [comment]
Thank you for reporting the issue! I'll just reopen it so that I don't forget to improve that error message 🙌
