### ISSUE TITLE
Error in importing plugin

### ISSUE THREAD

**Issue by JB4Jaison** [haesleinhuepf/napari-accelerated-pixel-and-object-classification#38]
Hello team,

I am getting an error while starting Napari. The plugin seems to not be available in the plugin menu. I am currently running Python 3.9 on a Windows machine. The stack trace of the Plugin Exception is as seen below.

====== Errors for plugin 'napari-accelerated-pixel-and-object-classification' ======

  napari version: 0.4.17

ERROR #1:  Error while importing module napari_accelerated_pixel_and_object_classification 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_plugin_engine\manager.py:318, in PluginManager._load_and_register(self=<napari.plugins._plugin_manager.NapariPluginManager object>, mod_name='napari_accelerated_pixel_and_object_classification', plugin_name='napari-accelerated-pixel-and-object-classification')
    317 try:
--> 318     module = load(mod_name)
        mod_name = 'napari_accelerated_pixel_and_object_classification'
    319     if self.is_registered(module):

File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_plugin_engine\manager.py:1042, in load(value='napari_accelerated_pixel_and_object_classification')
   1041     raise ValueError(f"malformed entry point string: {value}")
-> 1042 module = importlib.import_module(match.group('module'))
        match = <re.Match object; span=(0, 50), match='napari_accelerated_pixel_and_object_classificatio>
   1043 attrs = filter(None, (match.group('attr') or '').split('.'))

File ~\Anaconda3\envs\napari-env\lib\importlib\__init__.py:127, in import_module(name='napari_accelerated_pixel_and_object_classification', package=None)
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)
        level = 0
        name = 'napari_accelerated_pixel_and_object_classification'
        name[level:] = 'napari_accelerated_pixel_and_object_classification'
        package = None
        _bootstrap = <module 'importlib._bootstrap' (frozen)>

File <frozen importlib._bootstrap>:1030, in _gcd_import(name='napari_accelerated_pixel_and_object_classification', package=None, level=0)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name='napari_accelerated_pixel_and_object_classification', import_=<function _gcd_import>)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name='napari_accelerated_pixel_and_object_classification', import_=<function _gcd_import>)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec=ModuleSpec(name='napari_accelerated_pixel_and_ob...ri_accelerated_pixel_and_object_classification']))

File <frozen importlib._bootstrap_external>:850, in exec_module(self=<_frozen_importlib_external.SourceFileLoader object>, module=<module 'napari_accelerated_pixel_and_object_cla...ed_pixel_and_object_classification\\__init__.py'>)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f=<built-in function exec>, *args=(<code object <module> at 0x000001E568E11660, fil...l_and_object_classification\__init__.py", line 1>, {'__builtins__': {'ArithmeticError': <class 'ArithmeticError'>, 'AssertionError': <class 'AssertionError'>, 'AttributeError': <class 'AttributeError'>, 'BaseException': <class 'BaseException'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'BufferError': <class 'BufferError'>, 'BytesWarning': <class 'BytesWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, ...}, '__cached__': r'C:\Users\jjohn\Anaconda3\envs\napari-env\lib\sit...lassification\__pycache__\__init__.cpython-39.pyc', '__doc__': None, '__file__': r'C:\Users\jjohn\Anaconda3\envs\napari-env\lib\sit...rated_pixel_and_object_classification\__init__.py', '__loader__': <_frozen_importlib_external.SourceFileLoader object>, '__name__': 'napari_accelerated_pixel_and_object_classification', '__package__': 'napari_accelerated_pixel_and_object_classification', '__path__': [r'C:\Users\jjohn\Anaconda3\envs\napari-env\lib\sit...apari_accelerated_pixel_and_object_classification'], '__spec__': ModuleSpec(name='napari_accelerated_pixel_and_ob...ri_accelerated_pixel_and_object_classification']), '__version__': '0.12.3'}), **kwds={})

File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_accelerated_pixel_and_object_classification\__init__.py:9
      4     __version__ = "0.12.3"
----> 9 from ._function import napari_experimental_provide_function
     10 from ._dock_widget import napari_experimental_provide_dock_widget

File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_accelerated_pixel_and_object_classification\_function.py:3
      1 import warnings
----> 3 from apoc import PredefinedFeatureSet, PixelClassifier, ObjectSegmenter, ObjectClassifier, ObjectSelector, ProbabilityMapper
      5 import numpy as np

File ~\Anaconda3\envs\napari-env\lib\site-packages\apoc\__init__.py:2
      1 from ._converter import RFC_to_OCL
----> 2 from ._pixel_classifier import PixelClassifier
      3 from ._object_segmenter import ObjectSegmenter

File ~\Anaconda3\envs\napari-env\lib\site-packages\apoc\_pixel_classifier.py:5
      4 from ._converter import RFC_to_OCL
----> 5 from ._utils import generate_feature_stack, _read_something_from_opencl_file
      8 class PixelClassifier():

File ~\Anaconda3\envs\napari-env\lib\site-packages\apoc\_utils.py:3
      1 from typing import Union
----> 3 import pyclesperanto_prototype as cle
      4 import inspect

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyclesperanto_prototype\__init__.py:1
----> 1 from ._tier0 import *
      2 from ._tier1 import *

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyclesperanto_prototype\_tier0\__init__.py:36
     35 from ._push import push as asarray
---> 36 from ._plugin_function import plugin_function
     37 from ._types import Image

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyclesperanto_prototype\_tier0\_plugin_function.py:8
      7 from ._create import create_like
----> 8 from ._types import Image, is_image
      9 from ._push import push

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyclesperanto_prototype\_tier0\_types.py:2
      1 import numpy as np
----> 2 from ._pycl import OCLArray, _OCLImage
      3 import pyopencl as cl

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyclesperanto_prototype\_tier0\_pycl.py:6
      5 import numpy as np
----> 6 import pyopencl as cl
      7 from pyopencl import characterize

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyopencl\__init__.py:30
     29 # must import, otherwise dtype registry will not be fully populated
---> 30 import pyopencl.cltypes  # noqa: F401
     32 import logging

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyopencl\cltypes.py:22
     21 import numpy as np
---> 22 from pyopencl.tools import get_or_register_dtype
     23 import warnings

File ~\Anaconda3\envs\napari-env\lib\site-packages\pyopencl\tools.py:137
    136 from pytools import memoize, memoize_method
--> 137 from pyopencl._cl import bitlog2, get_cl_header_version  # noqa: F401
    138 from pytools.persistent_dict import KeyBuilder as KeyBuilderBase

ImportError: DLL load failed while importing _cl: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

PluginImportError                         Traceback (most recent call last)
File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_plugin_engine\manager.py:264, in PluginManager.discover(self=<napari.plugins._plugin_manager.NapariPluginManager object>, path=None, entry_point=None, prefix=None, ignore_errors=True)
    261     continue
    263 try:
--> 264     if self._load_and_register(mod_name, name):
        name = 'napari-tools-menu'
        mod_name = 'napari_tools_menu'
        self = <napari.plugins._plugin_manager.NapariPluginManager object at 0x000001E568BF4910>
    265         count += 1
    266         self._id_counts[name] = 1

File ~\Anaconda3\envs\napari-env\lib\site-packages\napari_plugin_engine\manager.py:322, in PluginManager._load_and_register(self=<napari.plugins._plugin_manager.NapariPluginManager object>, mod_name='napari_accelerated_pixel_and_object_classification', plugin_name='napari-accelerated-pixel-and-object-classification')
    320         return None
    321 except Exception as exc:
--> 322     raise PluginImportError(
        mod_name = 'napari_accelerated_pixel_and_object_classification'
        plugin_name = 'napari-accelerated-pixel-and-object-classification'
    323         f'Error while importing module {mod_name}',
    324         plugin_name=plugin_name,
    325         cause=exc,
    326     )
    327 if not (inspect.isclass(module) or inspect.ismodule(module)):
    328     raise PluginRegistrationError(
    329         f'Plugin "{plugin_name}" declared entry_point "{mod_name}"'
    330         ' which is neither a module nor a class.',
    331         plugin=module,
    332         plugin_name=plugin_name,
    333     )

PluginImportError: Error while importing module napari_accelerated_pixel_and_object_classification
================================================================================
================================================================================

**Comment by haesleinhuepf** [comment]
Hi @JB4Jaison ,

this error appears related to an issue in pyopencl:
https://github.com/inducer/pyopencl/issues/442

Can you try to update the driver of your graphics card? 

Please let us know if this helps!

Best,
Robert

**Comment by JB4Jaison** [comment]
Thank you for your quick reply. I will get onto that and see how it goes.
